// ui/src/main.tsx
import { StrictMode } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import './main.css';
import App from './app';

const queryClient = new QueryClient({
	defaultOptions: {
		queries: {
			staleTime: Infinity,
		},
	},
});

export const AppElement = (
	<QueryClientProvider client={queryClient}>
		<StrictMode>
			<App />
			<ReactQueryDevtools initialIsOpen={false} buttonPosition="bottom-left" />
		</StrictMode>
	</QueryClientProvider>
);

// ui-solid/src/index.tsx
/* @refresh reload */
import { render } from 'solid-js/web';
import { QueryClient, QueryClientProvider } from '@tanstack/solid-query';
import { SolidQueryDevtools } from '@tanstack/solid-query-devtools';
import './index.css';
import App from './App';

const queryClient = new QueryClient({
	defaultOptions: {
		queries: {
			staleTime: Infinity,
		},
	},
});

render(
	() => (
		<QueryClientProvider client={queryClient}>
			<App />
			<SolidQueryDevtools />
		</QueryClientProvider>
	),
	document.getElementById('root') as HTMLElement,
);
